image: ruby:2.4.2

cache:
  paths:
    - cache

before_script:
  - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler -v 1.15.4 --no-ri --no-rdoc
  - bundle install -j $(nproc) --path cache

test:
  script:
    - bundle exec rake test_app
    - rspec spec
